import { useEffect, useState } from "react";
import axios from "axios";
import { AlertCircle, BarChart3, Shield, AlertTriangle, CheckCircle, RefreshCw, Download, Share2 } from "lucide-react";
import { toast } from "react-toastify";

export default function Insights() {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [refreshing, setRefreshing] = useState(false);

  const fetchInsights = async () => {
    try {
      setLoading(true);
      setError(null);
      const userId = localStorage.getItem("userId");
      
      if (!userId) {
        throw new Error("User not authenticated");
      }

      const token = localStorage.getItem("token");
      const response = await axios.post(
        `${import.meta.env.VITE_API_BASE_URL}/api/insights/generate`,
        { userId },
        { headers: token ? { Authorization: `Bearer ${token}` } : {} }
      );

      if (response.data && response.data.success !== false) {
        // Ensure all required fields have defaults
        setInsights({
          totalLogs: response.data.totalLogs || 0,
          errorLogs: response.data.errorLogs || 0,
          suspiciousIPs: response.data.suspiciousIPs || 0,
          totalReports: response.data.totalReports || 0,
          summary: response.data.summary || "No insights available yet.",
          recommendation: response.data.recommendation || "Upload log files to generate insights.",
          ...response.data
        });
      } else {
        throw new Error(response.data?.message || "Failed to generate insights");
      }
    } catch (err) {
      const errorMessage = err.response?.data?.message || err.message || "Failed to generate insights";
      setError(errorMessage);
      toast.error(errorMessage);
      console.error("Insights Error:", err);
    } finally {
      setLoading(false);
    }
  };

  const refreshInsights = async () => {
    try {
      setRefreshing(true);
      await fetchInsights();
      toast.success("Insights refreshed successfully!");
    } catch (err) {
      toast.error("Failed to refresh insights");
    } finally {
      setRefreshing(false);
    }
  };

  const shareInsights = async () => {
    try {
      if (!insights) return;
      
      const insightsText = `
Security Insights Report

📊 Analysis Summary:
• Total Logs: ${insights.totalLogs || 0}
• Error Logs: ${insights.errorLogs || 0}
• Suspicious IPs: ${insights.suspiciousIPs || 0}

📝 Summary: ${insights.summary || 'No summary available'}

💡 Recommendation: ${insights.recommendation || 'No recommendations available'}

Generated by Secure Log Analyzer
      `.trim();

      if (navigator.share) {
        await navigator.share({
          title: 'Security Insights Report',
          text: insightsText,
        });
      } else {
        await navigator.clipboard.writeText(insightsText);
        toast.success('Insights copied to clipboard!');
      }
    } catch (err) {
      toast.error('Failed to share insights');
    }
  };

  const downloadReport = () => {
    if (!insights) return;

    const reportContent = `
SECURITY INSIGHTS REPORT
Generated on: ${new Date().toLocaleString()}

ANALYSIS SUMMARY
================
Total Logs Processed: ${insights.totalLogs || 0}
Error Logs Found: ${insights.errorLogs || 0}
Suspicious IP Addresses: ${insights.suspiciousIPs || 0}

DETAILED ANALYSIS
=================
${insights.summary || 'No detailed summary available.'}

RECOMMENDATIONS
===============
${insights.recommendation || 'No specific recommendations available.'}

SECURITY ASSESSMENT
===================
Risk Level: ${insights.suspiciousIPs > 10 ? 'HIGH' : insights.suspiciousIPs > 5 ? 'MEDIUM' : 'LOW'}
Status: ${insights.errorLogs > 100 ? 'CRITICAL ATTENTION REQUIRED' : insights.errorLogs > 50 ? 'REVIEW RECOMMENDED' : 'NORMAL'}

Next Steps:
- ${insights.suspiciousIPs > 5 ? '⚠️  Investigate suspicious IP addresses immediately' : '✓ Monitor IP addresses regularly'}
- ${insights.errorLogs > 50 ? '⚠️  Review and address error patterns in your logs' : '✓ Continue monitoring error rates'}
- ${insights.totalLogs > 1000 ? '⚠️  Consider implementing log rotation and archival strategies' : '✓ Log volume is within normal parameters'}

This report was generated by Secure Log Analyzer.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `security-insights-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success('Report downloaded successfully!');
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  // Auto-refresh insights periodically for near real-time updates
  useEffect(() => {
    const interval = setInterval(() => {
      fetchInsights();
    }, 30000);
    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-2">
            Generating Security Insights
          </h2>
          <p className="text-gray-600 dark:text-gray-300">
            Analyzing your log data for patterns and security threats...
          </p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
        <div className="max-w-4xl mx-auto px-4">
          <div className="bg-red-50 dark:bg-red-900 border border-red-200 dark:border-red-800 rounded-xl p-6 text-center">
            <AlertCircle className="w-16 h-16 text-red-600 dark:text-red-400 mx-auto mb-4" />
            <h2 className="text-2xl font-bold text-red-800 dark:text-red-200 mb-2">
              Failed to Generate Insights
            </h2>
            <p className="text-red-700 dark:text-red-300 mb-4">
              {error}
            </p>
            <button
              onClick={fetchInsights}
              className="inline-flex items-center gap-2 px-6 py-3 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
              Try Again
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!insights) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <AlertCircle className="w-16 h-16 text-yellow-600 dark:text-yellow-400 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
            No Insights Available
          </h2>
          <p className="text-gray-600 dark:text-gray-300 mb-4">
            Upload some log files to generate insights.
          </p>
          <button
            onClick={() => window.location.href = '/dashboard'}
            className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            Go to Dashboard
          </button>
        </div>
      </div>
    );
  }

  const riskLevel = insights.suspiciousIPs > 10 ? 'high' : insights.suspiciousIPs > 5 ? 'medium' : 'low';
  const status = insights.errorLogs > 100 ? 'critical' : insights.errorLogs > 50 ? 'warning' : 'good';

  const getRiskColor = (level) => {
    switch (level) {
      case 'high': return 'text-red-600 dark:text-red-400 bg-red-100 dark:bg-red-900';
      case 'medium': return 'text-yellow-600 dark:text-yellow-400 bg-yellow-100 dark:bg-yellow-900';
      case 'low': return 'text-green-600 dark:text-green-400 bg-green-100 dark:bg-green-900';
      default: return 'text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-900';
    }
  };

  const getStatusIcon = (status) => {
    switch (status) {
      case 'critical': return <AlertTriangle className="w-6 h-6 text-red-600 dark:text-red-400" />;
      case 'warning': return <AlertCircle className="w-6 h-6 text-yellow-600 dark:text-yellow-400" />;
      case 'good': return <CheckCircle className="w-6 h-6 text-green-600 dark:text-green-400" />;
      default: return <BarChart3 className="w-6 h-6 text-blue-600 dark:text-blue-400" />;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
      <div className="max-w-6xl mx-auto px-4">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
              🔍 Security Insights
            </h1>
            <p className="text-gray-600 dark:text-gray-300">
              Comprehensive analysis of your log data with actionable recommendations
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={refreshInsights}
              disabled={refreshing}
              className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              <RefreshCw className={`w-4 h-4 ${refreshing ? 'animate-spin' : ''}`} />
              Refresh
            </button>
            <button
              onClick={shareInsights}
              className="inline-flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
            >
              <Share2 className="w-4 h-4" />
              Share
            </button>
            <button
              onClick={downloadReport}
              className="inline-flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>

        {/* Status Overview */}
        <div className="grid md:grid-cols-3 gap-6 mb-8">
          {/* Overall Status */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <div className="flex items-center gap-3 mb-4">
              {getStatusIcon(status)}
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                System Status
              </h3>
            </div>
            <div className="text-2xl font-bold text-gray-900 dark:text-white mb-1">
              {status === 'critical' ? 'CRITICAL' : status === 'warning' ? 'WARNING' : 'HEALTHY'}
            </div>
            <p className="text-sm text-gray-600 dark:text-gray-300">
              {status === 'critical' ? 'Immediate attention required' : status === 'warning' ? 'Review recommended' : 'All systems normal'}
            </p>
          </div>

          {/* Risk Assessment */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-6 h-6 text-blue-600 dark:text-blue-400" />
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                Risk Level
              </h3>
            </div>
            <div className={`text-2xl font-bold mb-1 ${getRiskColor(riskLevel).split(' ')[0]}`}>
              {riskLevel.toUpperCase()}
            </div>
            <p className="text-sm text-gray-600 dark:text-gray-300">
              Based on suspicious IP activity
            </p>
          </div>

          {/* Log Summary */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <div className="flex items-center gap-3 mb-4">
              <BarChart3 className="w-6 h-6 text-green-600 dark:text-green-400" />
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                Log Summary
              </h3>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-gray-600 dark:text-gray-300">Total Logs:</span>
                <span className="font-semibold text-gray-900 dark:text-white">{insights.totalLogs || 0}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-600 dark:text-gray-300">Error Rate:</span>
                <span className={`font-semibold ${insights.totalLogs > 0 ? (insights.errorLogs / insights.totalLogs * 100 > 10 ? 'text-red-600 dark:text-red-400' : 'text-green-600 dark:text-green-400') : 'text-gray-900 dark:text-white'}`}>
                  {insights.totalLogs > 0 ? `${((insights.errorLogs || 0) / insights.totalLogs * 100).toFixed(1)}%` : '0%'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Detailed Insights */}
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Analysis Summary */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
              📊 Analysis Summary
            </h3>
            <div className="space-y-4">
              <div className="flex justify-between items-center py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-300">Total Logs Processed:</span>
                <span className="font-semibold text-gray-900 dark:text-white">{insights.totalLogs || 0}</span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-300">Error Logs Found:</span>
                <span className={`font-semibold ${insights.errorLogs > 50 ? 'text-red-600 dark:text-red-400' : 'text-gray-900 dark:text-white'}`}>
                  {insights.errorLogs || 0}
                </span>
              </div>
              <div className="flex justify-between items-center py-2 border-b border-gray-200 dark:border-gray-700">
                <span className="text-gray-600 dark:text-gray-300">Suspicious IP Addresses:</span>
                <span className={`font-semibold ${insights.suspiciousIPs > 5 ? 'text-red-600 dark:text-red-400' : 'text-gray-900 dark:text-white'}`}>
                  {insights.suspiciousIPs || 0}
                </span>
              </div>
              <div className="flex justify-between items-center py-2">
                <span className="text-gray-600 dark:text-gray-300">Analysis Date:</span>
                <span className="font-semibold text-gray-900 dark:text-white">
                  {new Date().toLocaleDateString()}
                </span>
              </div>
            </div>
          </div>

          {/* Recommendations */}
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
              💡 Recommendations
            </h3>
            <div className="space-y-3">
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                {insights.recommendation || 'No specific recommendations available at this time.'}
              </p>
              
              {/* Additional context-based recommendations */}
              {insights.suspiciousIPs > 5 && (
                <div className="bg-red-50 dark:bg-red-900 border border-red-200 dark:border-red-800 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <AlertTriangle className="w-5 h-5 text-red-600 dark:text-red-400" />
                    <span className="font-semibold text-red-800 dark:text-red-200">
                      Security Alert
                    </span>
                  </div>
                  <p className="text-red-700 dark:text-red-300 text-sm">
                    High number of suspicious IP addresses detected. Consider implementing IP blocking or rate limiting.
                  </p>
                </div>
              )}
              
              {insights.errorLogs > 50 && (
                <div className="bg-yellow-50 dark:bg-yellow-900 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <AlertCircle className="w-5 h-5 text-yellow-600 dark:text-yellow-400" />
                    <span className="font-semibold text-yellow-800 dark:text-yellow-200">
                      Performance Warning
                    </span>
                  </div>
                  <p className="text-yellow-700 dark:text-yellow-300 text-sm">
                    Elevated error rate detected. Review application logs and consider error handling improvements.
                  </p>
                </div>
              )}
              
              {insights.totalLogs > 1000 && (
                <div className="bg-blue-50 dark:bg-blue-900 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <BarChart3 className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                    <span className="font-semibold text-blue-800 dark:text-blue-200">
                      Volume Notice
                    </span>
                  </div>
                  <p className="text-blue-700 dark:text-blue-300 text-sm">
                    High log volume detected. Consider implementing log rotation and archival strategies.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Summary Section */}
        <div className="mt-8 bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-4">
            📝 Executive Summary
          </h3>
          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            {insights.summary || 'No detailed summary available for your log analysis.'}
          </p>
        </div>
      </div>
    </div>
  );
}
